
import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "es" | "fr" | "sw";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    market: "Market Prices",
    weather: "Weather",
    support: "Support",
    settings: "Settings",
    login: "Login",
    register: "Register",
    welcomeMessage: "Welcome to Farmer Focus Connect",
    marketPrices: "Market Prices",
    weatherForecast: "Weather Forecast",
    logout: "Logout",
    askQuestion: "Ask a Question",
    priceUpdates: "Price Updates",
    today: "Today",
    tomorrow: "Tomorrow",
    username: "Username",
    password: "Password",
    email: "Email",
    phone: "Phone Number",
    region: "Region",
    submit: "Submit",
    cancel: "Cancel",
    chats: "Chats",
    connectWithFarmersAndBuyers: "Connect with farmers and buyers",
    noChatsYet: "No chats yet",
    noChatsDescription: "Start browsing the marketplace to connect with other users",
    browseMarketplace: "Browse Marketplace",
    searchChats: "Search chats",
    marketplace: "Marketplace",
    buyFromFarmers: "Buy directly from farmers",
    loginToContact: "Login to contact sellers",
    loginToContactDesc: "Sign in to message sellers and view contact information",
    searchCrops: "Search crops",
    crop: "Crop",
    price: "Price",
    change: "Change",
    noCropsFound: "No crops found",
    allRegions: "All Regions",
    selectRegion: "Select Region",
    result: "result",
    results: "results",
    lastUpdated: "Last updated",
    quantity: "Quantity",
    description: "Description",
    postedOn: "Posted on",
    contactInfo: "Contact Information",
    noContactInfo: "No contact information provided",
    hideContact: "Hide Contact",
    viewContact: "View Contact",
    chat: "Chat",
    connecting: "Connecting",
    yourListing: "Your Listing",
    loginRequired: "Login required",
    contactInfoShown: "Contact information shown",
    cannotChatWithYourself: "You cannot chat with yourself",
    startingChat: "Starting chat",
    errorStartingChat: "Error starting chat",
    errorFetchingMarketData: "Error fetching market data",
    regionPreferenceUpdated: "Region preference updated",
    errorSavingPreference: "Error saving preference",
    errorLoadingChat: "Error loading chat",
    errorLoadingMessages: "Error loading messages",
    errorSendingMessage: "Error sending message",
    user: "User",
    loadingMessages: "Loading messages",
    noMessages: "No messages yet",
    sendFirstMessage: "Send the first message to start the conversation",
    typeMessage: "Type a message",
    errorFetchingChats: "Error fetching chats",
    errorFetchingListings: "Error fetching listings",
    viewAllPrices: "View All Prices",
    loading: "Loading",
    availableCrops: "Available Crops",
    postCrop: "Post Crop",
    noListingsFound: "No listings found",
    postYourCrops: "Post Your Crops",
    sortBy: "Sort by",
    newest: "Newest",
    oldest: "Oldest",
    postCropListing: "Post Crop Listing",
    shareYourProduceWithBuyers: "Share your produce with buyers",
    productInformation: "Product Information",
    cropName: "Crop Name",
    enterCropName: "Enter crop name",
    unit: "Unit",
    selectUnit: "Select unit",
    pricePerUnit: "Price Per Unit",
    location: "Location",
    productDescription: "Product Description",
    describeYourCrop: "Describe your crop",
    includeQualityAndFreshness: "Include quality and freshness details",
    contactInformation: "Contact Information",
    phoneNumber: "Phone Number",
    enterPhoneNumber: "Enter phone number",
    phoneOptional: "Optional",
    enterEmail: "Enter email",
    emailOptional: "Optional",
    postListing: "Post Listing",
    mustBeLoggedIn: "You must be logged in to post",
    cropListingPosted: "Crop listing posted successfully",
    errorPostingListing: "Error posting listing",
    name: "Name",
    updateProfile: "Update Profile",
    profileUpdated: "Profile updated successfully",
    errorUpdatingProfile: "Error updating profile",
  },
  es: {
    home: "Inicio",
    market: "Precios del Mercado",
    weather: "Clima",
    support: "Soporte",
    settings: "Configuración",
    login: "Iniciar Sesión",
    register: "Registrarse",
    welcomeMessage: "Bienvenido a Farmer Focus Connect",
    marketPrices: "Precios del Mercado",
    weatherForecast: "Pronóstico del Tiempo",
    logout: "Cerrar Sesión",
    askQuestion: "Hacer una Pregunta",
    priceUpdates: "Actualizaciones de Precios",
    today: "Hoy",
    tomorrow: "Mañana",
    username: "Nombre de Usuario",
    password: "Contraseña",
    email: "Correo Electrónico",
    phone: "Número de Teléfono",
    region: "Región",
    submit: "Enviar",
    cancel: "Cancelar",
    chats: "Chats",
    connectWithFarmersAndBuyers: "Conéctate con agricultores y compradores",
    noChatsYet: "Aún no hay chats",
    noChatsDescription: "Comienza a navegar por el mercado para conectarte con otros usuarios",
    browseMarketplace: "Explorar Mercado",
    searchChats: "Buscar chats",
    marketplace: "Mercado",
    buyFromFarmers: "Compra directamente a los agricultores",
    loginToContact: "Inicia sesión para contactar vendedores",
    loginToContactDesc: "Inicia sesión para enviar mensajes a los vendedores y ver su información de contacto",
    searchCrops: "Buscar cultivos",
    crop: "Cultivo",
    price: "Precio",
    change: "Cambio",
    noCropsFound: "No se encontraron cultivos",
    allRegions: "Todas las Regiones",
    selectRegion: "Seleccionar Región",
    result: "resultado",
    results: "resultados",
    lastUpdated: "Última actualización",
    quantity: "Cantidad",
    description: "Descripción",
    postedOn: "Publicado el",
    contactInfo: "Información de Contacto",
    noContactInfo: "No se proporcionó información de contacto",
    hideContact: "Ocultar Contacto",
    viewContact: "Ver Contacto",
    chat: "Chat",
    connecting: "Conectando",
    yourListing: "Tu Anuncio",
    loginRequired: "Inicio de sesión requerido",
    contactInfoShown: "Información de contacto mostrada",
    cannotChatWithYourself: "No puedes chatear contigo mismo",
    startingChat: "Iniciando chat",
    errorStartingChat: "Error al iniciar chat",
    errorFetchingMarketData: "Error al obtener datos del mercado",
    regionPreferenceUpdated: "Preferencia de región actualizada",
    errorSavingPreference: "Error al guardar preferencia",
    errorLoadingChat: "Error al cargar chat",
    errorLoadingMessages: "Error al cargar mensajes",
    errorSendingMessage: "Error al enviar mensaje",
    user: "Usuario",
    loadingMessages: "Cargando mensajes",
    noMessages: "Aún no hay mensajes",
    sendFirstMessage: "Envía el primer mensaje para iniciar la conversación",
    typeMessage: "Escribe un mensaje",
    errorFetchingChats: "Error al obtener chats",
    errorFetchingListings: "Error al obtener anuncios",
    viewAllPrices: "Ver Todos los Precios",
    loading: "Cargando",
    availableCrops: "Cultivos Disponibles",
    postCrop: "Publicar Cultivo",
    noListingsFound: "No se encontraron anuncios",
    postYourCrops: "Publica Tus Cultivos",
    sortBy: "Ordenar por",
    newest: "Más Reciente",
    oldest: "Más Antiguo",
    postCropListing: "Publicar Anuncio de Cultivo",
    shareYourProduceWithBuyers: "Comparte tu producto con compradores",
    productInformation: "Información del Producto",
    cropName: "Nombre del Cultivo",
    enterCropName: "Ingresa el nombre del cultivo",
    unit: "Unidad",
    selectUnit: "Seleccionar unidad",
    pricePerUnit: "Precio por Unidad",
    location: "Ubicación",
    productDescription: "Descripción del Producto",
    describeYourCrop: "Describe tu cultivo",
    includeQualityAndFreshness: "Incluye detalles de calidad y frescura",
    contactInformation: "Información de Contacto",
    phoneNumber: "Número de Teléfono",
    enterPhoneNumber: "Ingresa tu número de teléfono",
    phoneOptional: "Opcional",
    enterEmail: "Ingresa tu correo electrónico",
    emailOptional: "Opcional",
    postListing: "Publicar Anuncio",
    mustBeLoggedIn: "Debes iniciar sesión para publicar",
    cropListingPosted: "Anuncio de cultivo publicado con éxito",
    errorPostingListing: "Error al publicar anuncio",
    name: "Nombre",
    updateProfile: "Actualizar Perfil",
    profileUpdated: "Perfil actualizado con éxito",
    errorUpdatingProfile: "Error al actualizar perfil",
  },
  fr: {
    home: "Accueil",
    market: "Prix du Marché",
    weather: "Météo",
    support: "Support",
    settings: "Paramètres",
    login: "Connexion",
    register: "S'inscrire",
    welcomeMessage: "Bienvenue sur Farmer Focus Connect",
    marketPrices: "Prix du Marché",
    weatherForecast: "Prévisions Météo",
    logout: "Déconnexion",
    askQuestion: "Poser une Question",
    priceUpdates: "Mises à jour des Prix",
    today: "Aujourd'hui",
    tomorrow: "Demain",
    username: "Nom d'Utilisateur",
    password: "Mot de Passe",
    email: "E-mail",
    phone: "Numéro de Téléphone",
    region: "Région",
    submit: "Soumettre",
    cancel: "Annuler",
    chats: "Discussions",
    connectWithFarmersAndBuyers: "Connectez-vous avec les agriculteurs et les acheteurs",
    noChatsYet: "Pas encore de discussions",
    noChatsDescription: "Commencez à parcourir le marché pour vous connecter avec d'autres utilisateurs",
    browseMarketplace: "Parcourir le Marché",
    searchChats: "Rechercher des discussions",
    marketplace: "Marché",
    buyFromFarmers: "Achetez directement auprès des agriculteurs",
    loginToContact: "Connectez-vous pour contacter les vendeurs",
    loginToContactDesc: "Connectez-vous pour envoyer des messages aux vendeurs et voir leurs coordonnées",
    searchCrops: "Rechercher des cultures",
    crop: "Culture",
    price: "Prix",
    change: "Changement",
    noCropsFound: "Aucune culture trouvée",
    allRegions: "Toutes les Régions",
    selectRegion: "Sélectionner une Région",
    result: "résultat",
    results: "résultats",
    lastUpdated: "Dernière mise à jour",
    quantity: "Quantité",
    description: "Description",
    postedOn: "Publié le",
    contactInfo: "Informations de Contact",
    noContactInfo: "Aucune information de contact fournie",
    hideContact: "Masquer le Contact",
    viewContact: "Voir le Contact",
    chat: "Discussion",
    connecting: "Connexion en cours",
    yourListing: "Votre Annonce",
    loginRequired: "Connexion requise",
    contactInfoShown: "Informations de contact affichées",
    cannotChatWithYourself: "Vous ne pouvez pas discuter avec vous-même",
    startingChat: "Démarrage de la discussion",
    errorStartingChat: "Erreur lors du démarrage de la discussion",
    errorFetchingMarketData: "Erreur lors de la récupération des données du marché",
    regionPreferenceUpdated: "Préférence de région mise à jour",
    errorSavingPreference: "Erreur lors de l'enregistrement de la préférence",
    errorLoadingChat: "Erreur lors du chargement de la discussion",
    errorLoadingMessages: "Erreur lors du chargement des messages",
    errorSendingMessage: "Erreur lors de l'envoi du message",
    user: "Utilisateur",
    loadingMessages: "Chargement des messages",
    noMessages: "Pas encore de messages",
    sendFirstMessage: "Envoyez le premier message pour démarrer la conversation",
    typeMessage: "Tapez un message",
    errorFetchingChats: "Erreur lors de la récupération des discussions",
    errorFetchingListings: "Erreur lors de la récupération des annonces",
    viewAllPrices: "Voir Tous les Prix",
    loading: "Chargement",
    availableCrops: "Cultures Disponibles",
    postCrop: "Publier une Culture",
    noListingsFound: "Aucune annonce trouvée",
    postYourCrops: "Publiez Vos Cultures",
    sortBy: "Trier par",
    newest: "Plus Récent",
    oldest: "Plus Ancien",
    postCropListing: "Publier une Annonce de Culture",
    shareYourProduceWithBuyers: "Partagez vos produits avec les acheteurs",
    productInformation: "Informations sur le Produit",
    cropName: "Nom de la Culture",
    enterCropName: "Entrez le nom de la culture",
    unit: "Unité",
    selectUnit: "Sélectionner l'unité",
    pricePerUnit: "Prix par Unité",
    location: "Emplacement",
    productDescription: "Description du Produit",
    describeYourCrop: "Décrivez votre culture",
    includeQualityAndFreshness: "Incluez les détails de qualité et de fraîcheur",
    contactInformation: "Informations de Contact",
    phoneNumber: "Numéro de Téléphone",
    enterPhoneNumber: "Entrez votre numéro de téléphone",
    phoneOptional: "Optionnel",
    enterEmail: "Entrez votre e-mail",
    emailOptional: "Optionnel",
    postListing: "Publier l'Annonce",
    mustBeLoggedIn: "Vous devez être connecté pour publier",
    cropListingPosted: "Annonce de culture publiée avec succès",
    errorPostingListing: "Erreur lors de la publication de l'annonce",
    name: "Nom",
    updateProfile: "Mettre à Jour le Profil",
    profileUpdated: "Profil mis à jour avec succès",
    errorUpdatingProfile: "Erreur lors de la mise à jour du profil",
  },
  sw: {
    home: "Nyumbani",
    market: "Bei za Soko",
    weather: "Hali ya Hewa",
    support: "Msaada",
    settings: "Mipangilio",
    login: "Ingia",
    register: "Jiandikishe",
    welcomeMessage: "Karibu kwenye Farmer Focus Connect",
    marketPrices: "Bei za Soko",
    weatherForecast: "Utabiri wa Hali ya Hewa",
    logout: "Toka",
    askQuestion: "Uliza Swali",
    priceUpdates: "Masasisho ya Bei",
    today: "Leo",
    tomorrow: "Kesho",
    username: "Jina la Mtumiaji",
    password: "Neno la Siri",
    email: "Barua Pepe",
    phone: "Nambari ya Simu",
    region: "Mkoa",
    submit: "Wasilisha",
    cancel: "Ghairi",
    chats: "Mazungumzo",
    connectWithFarmersAndBuyers: "Unganisha na wakulima na wanunuzi",
    noChatsYet: "Hakuna mazungumzo bado",
    noChatsDescription: "Anza kuvinjari soko ili kuungana na watumiaji wengine",
    browseMarketplace: "Vinjari Soko",
    searchChats: "Tafuta mazungumzo",
    marketplace: "Soko",
    buyFromFarmers: "Nunua moja kwa moja kutoka kwa wakulima",
    loginToContact: "Ingia ili kuwasiliana na wauzaji",
    loginToContactDesc: "Ingia ili kutuma ujumbe kwa wauzaji na kuona maelezo ya mawasiliano",
    searchCrops: "Tafuta mazao",
    crop: "Zao",
    price: "Bei",
    change: "Mabadiliko",
    noCropsFound: "Hakuna mazao yaliyopatikana",
    allRegions: "Mikoa Yote",
    selectRegion: "Chagua Mkoa",
    result: "matokeo",
    results: "matokeo",
    lastUpdated: "Imesasishwa mwisho",
    quantity: "Kiasi",
    description: "Maelezo",
    postedOn: "Imechapishwa",
    contactInfo: "Maelezo ya Mawasiliano",
    noContactInfo: "Hakuna maelezo ya mawasiliano yaliyotolewa",
    hideContact: "Ficha Mawasiliano",
    viewContact: "Tazama Mawasiliano",
    chat: "Mazungumzo",
    connecting: "Inaunganisha",
    yourListing: "Tangazo Lako",
    loginRequired: "Unahitaji kuingia",
    contactInfoShown: "Maelezo ya mawasiliano yanaonyeshwa",
    cannotChatWithYourself: "Huwezi kuzungumza na wewe mwenyewe",
    startingChat: "Inaanza mazungumzo",
    errorStartingChat: "Hitilafu katika kuanza mazungumzo",
    errorFetchingMarketData: "Hitilafu katika kupata data ya soko",
    regionPreferenceUpdated: "Chaguo la mkoa limesasishwa",
    errorSavingPreference: "Hitilafu katika kuhifadhi chaguo",
    errorLoadingChat: "Hitilafu katika kupakia mazungumzo",
    errorLoadingMessages: "Hitilafu katika kupakia ujumbe",
    errorSendingMessage: "Hitilafu katika kutuma ujumbe",
    user: "Mtumiaji",
    loadingMessages: "Inapakia ujumbe",
    noMessages: "Hakuna ujumbe bado",
    sendFirstMessage: "Tuma ujumbe wa kwanza ili kuanza mazungumzo",
    typeMessage: "Andika ujumbe",
    errorFetchingChats: "Hitilafu katika kupata mazungumzo",
    errorFetchingListings: "Hitilafu katika kupata matangazo",
    viewAllPrices: "Tazama Bei Zote",
    loading: "Inapakia",
    availableCrops: "Mazao Yanayopatikana",
    postCrop: "Chapisha Zao",
    noListingsFound: "Hakuna matangazo yaliyopatikana",
    postYourCrops: "Chapisha Mazao Yako",
    sortBy: "Panga kwa",
    newest: "Mpya Zaidi",
    oldest: "Za Zamani Zaidi",
    postCropListing: "Chapisha Tangazo la Zao",
    shareYourProduceWithBuyers: "Shiriki mazao yako na wanunuzi",
    productInformation: "Maelezo ya Bidhaa",
    cropName: "Jina la Zao",
    enterCropName: "Weka jina la zao",
    unit: "Kipimo",
    selectUnit: "Chagua kipimo",
    pricePerUnit: "Bei kwa Kipimo",
    location: "Mahali",
    productDescription: "Maelezo ya Bidhaa",
    describeYourCrop: "Eleza zao lako",
    includeQualityAndFreshness: "Jumuisha maelezo ya ubora na ugaridi",
    contactInformation: "Maelezo ya Mawasiliano",
    phoneNumber: "Nambari ya Simu",
    enterPhoneNumber: "Weka nambari yako ya simu",
    phoneOptional: "Si lazima",
    enterEmail: "Weka barua pepe yako",
    emailOptional: "Si lazima",
    postListing: "Chapisha Tangazo",
    mustBeLoggedIn: "Lazima uingie ili kuchapisha",
    cropListingPosted: "Tangazo la zao limechapishwa kwa mafanikio",
    errorPostingListing: "Hitilafu katika kuchapisha tangazo",
    name: "Jina",
    updateProfile: "Sasisha Wasifu",
    profileUpdated: "Wasifu umesasishwa kwa mafanikio",
    errorUpdatingProfile: "Hitilafu katika kusasisha wasifu",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    const storedLanguage = localStorage.getItem("farmer-language") as Language;
    if (storedLanguage && Object.keys(translations).includes(storedLanguage)) {
      setLanguage(storedLanguage);
    }
  }, []);

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("farmer-language", lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageProvider;
